#FROM openjdk:11-jre-slim AS builder
#FROM eclipse-temurin:17-jre as temurin-17-jre
FROM openjdk:17 as builder

WORKDIR /users/apps/carrotdata/memcarrot

# copy binary code
COPY ./target/memcarrot-0.11-SNAPSHOT-jar-with-dependencies.jar /users/apps/carrotdata/memcarrot

# Build small JRE image
RUN jlink --compress 2 --strip-debug --no-header-files --no-man-pages --add-modules java.base --output /users/apps/carrotdata/memcarrot-jre-builder

# Stage 2: Create the runtime image using the JRE created by jlink
FROM debian:buster-slim

# Copy the custom JRE from the builder stage
COPY --from=builder /users/apps/carrotdata/memcarrot-jre-builder /users/apps/carrotdata/memcarrot-jre

# Set the custom Java runtime as the PATH
#ENV PATH=".:/users/apps/carrotdata/memcarrot-jre/bin:${PATH}"

# copy start helper scripts
COPY bin_docker_runtime/memcarrot.sh /users/apps/carrotdata/memcarrot
COPY bin_docker_runtime/setenv.sh /users/apps/carrotdata/memcarrot

EXPOSE 11211

ENTRYPOINT ["/bin/bash"]
CMD ["./memcarrot.sh"]
