services:
  memcarrot:
    build: docker
    image: carrotdata/memcarrot:latest-arm64
    container_name: memcarrot
    environment:
      - JMX_EXPORTER_ENABLED=true
      - server.address=0.0.0.0
    volumes:
      - ./bin/setenv_4docker.sh:/users/carrotdata/memcarrot/bin/setenv.sh
      - ./conf/memcarrot.cfg:/users/carrotdata/memcarrot/conf/memcarrot.cfg
      - ./jmx/jmxconfig.yml:/users/carrotdata/memcarrot/conf/jmxconfig.yml
      - ./data:/users/carrotdata/memcarrot/data
      - ./logs:/users/carrotdata/memcarrot/logs
    ports:
      - "11211:11211"  # Application port
      - "9191:9191"  # Memcached exporter port
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
