global:
  scrape_interval: 10s  # How frequently to scrape targets by default
  evaluation_interval: 10s  # How frequently to evaluate rules

scrape_configs:
  - job_name: 'memcarrot_store'
    static_configs:
      - targets: ['host.docker.internal:9191']

